mapping:
  template:
    mappings:
      dynamic_templates:
        - pids:
            path_match: pids.*
            match_mapping_type: object
            mapping:
              type: object
              properties:
                identifier:
                  type: text
                  fields:
                    keyword:
                      type: keyword
                      ignore_above: 256
                provider:
                  type: keyword
                client:
                  type: keyword
        - parent_pids:
            path_match: parent.pids.*
            match_mapping_type: object
            mapping:
              type: object
              properties:
                identifier:
                  type: text
                  fields:
                    keyword:
                      type: keyword
                      ignore_above: 256
                provider:
                  type: keyword
                client:
                  type: keyword
