name: Build NR model

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Build package to publish
        run: ./build.sh

      - name: Archive production nr-metadata artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nr_metadata_dist
          path: packages/nr-metadata/dist

      - name: Archive production omb-nr artifacts
        uses: actions/upload-artifact@v3
        with:
          name: omb_nr_dist
          path: packages/oarepo-model-builder-nr/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use built nr-metadata artifacts
        uses: actions/download-artifact@v3
        with:
          name: nr_metadata_dist
          path: nr_metadata_dist
      - name: Use built omb-nr artifacts
        uses: actions/download-artifact@v3
        with:
          name: omb_nr_dist
          path: omb_nr_dist

      - name: Publish nr-metadta package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: nr_metadata_dist

      - name: Publish omb-nr package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: omb_nr_dist
